import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { FiLinkedin, FiTwitter, FiGithub } from 'react-icons/fi';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ryan Lima</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className={styles.main}>
        <div className={styles.container}>
          <div className={styles.hello}>
            <div className={styles.avatar}>
              <Image src="/profile.jpg" alt="Ryan Lima" width={150} height={150} />
            </div>
            <h1>Ryan Lima</h1>
            <h2>Sou UI Designer e desenvolvedor FullStack</h2>
            <button type="button">
              Vamos trabalhar juntos
            </button>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export default Home
