import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ryan Lima</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className={styles.main}>
        <div className={styles.container}>
          <div className={styles.hello}>
            <div className={styles.avatar}>
              <Link href="https://github.com/ryansldev" passHref={true}>
                <a target="_blank">
                  <Image src="/profile.jpg" alt="Ryan Lima" width={200} height={200} />
                </a>
              </Link>
            </div>
            <h1>Ryan Lima</h1>
            <h2 style={{ marginBottom: '0.3em' }}>Sou UI Designer e desenvolvedor FullStack</h2>
            <Link passHref={true} href="#">
              <div className={styles.letsWorkTogether}>
                <div className={styles.scrollToIcon}>
                </div>
                Veja mais abaixo
              </div>
            </Link>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export default Home
